repos:
#   - repo: https://github.com/psf/black
#     rev: 24.10.0
#     hooks:
#       - id: black
#
#   - repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.7.4
#     hooks:
#       - id: ruff
#         args: [--fix]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -u -m pytest -v -ra
        language: system
        pass_filenames: false
